version: '3'
services:
  db:
    image: postgres:16-alpine
    container_name: portfolio-db
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - portfolio-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - portfolio-net

  db-admin:
    image: dpage/pgadmin4
    container_name: portfolio-db-admin
    restart: unless-stopped
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
    ports:
      - 8000:80
    networks:
      - portfolio-net
    depends_on:
      - db

  backend:
    container_name: portfolio-backend
    restart: unless-stopped
    build: .
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: portfolio-db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - 1337:1337
    networks:
      - portfolio-net
    depends_on:
      - db

  frontend:
    container_name: portfolio-frontend
    restart: unless-stopped
    build: '../frontend'
    ports:
      - 3000:3000
    networks:
      - portfolio-net
    depends_on:
      - db
      - backend

volumes:
  portfolio-data:

networks:
  portfolio-net:
    name: portfolio-net
    driver: bridge